/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.edubeans.action.panel;

import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import javax.swing.JOptionPane;
import org.openide.awt.HtmlBrowser;
import org.openide.util.Exceptions;


/**
 *
 * @author Teodora
 */
public class GooglePanel extends javax.swing.JPanel {

    /**
     * Creates new form GooglePanel
     */
    public GooglePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGoogleSearch = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GooglePanel.class, "GooglePanel.jLabel1.text")); // NOI18N

        txtGoogleSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtGoogleSearch.setText(org.openide.util.NbBundle.getMessage(GooglePanel.class, "GooglePanel.txtGoogleSearch.text")); // NOI18N
        txtGoogleSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGoogleSearchMouseClicked(evt);
            }
        });
        txtGoogleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGoogleSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGoogleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGoogleSearch)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGoogleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGoogleSearchActionPerformed
        try {
        String searchText = URLEncoder.encode(txtGoogleSearch.getText(), "UTF-8");
            HtmlBrowser.URLDisplayer.getDefault().showURL(new URL("https://www.google.com/search?q=" + searchText));
    } catch (UnsupportedEncodingException | MalformedURLException e) {
            JOptionPane.showMessageDialog(this, "Sorry. Something went wrong. Google search is not available at the moment.\nPlease try again later.", 
                    "Google search error", JOptionPane.ERROR_MESSAGE);
    }   
    }//GEN-LAST:event_txtGoogleSearchActionPerformed

    private void txtGoogleSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGoogleSearchMouseClicked
        txtGoogleSearch.setText("");
    }//GEN-LAST:event_txtGoogleSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtGoogleSearch;
    // End of variables declaration//GEN-END:variables
}
